### ISSUE TITLE
Blocks used have all NaN values in UEFI but not in AMD using Fiedka zip release 1.3.4

### ISSUE THREAD

**Issue by AkechiShiro** [fiedka/fiedka#76]
Hi,

I've just tried the Fiedka Electron app, I'm probably missing some dependencies or step since running `npm start` led to an error, I thus downloaded the latest zip release and launched it.
I took a binary bios ROM file, I dumped and noticed something weird : 
![image](https://user-images.githubusercontent.com/14914796/167248796-7f359a6f-82df-4891-b21f-83c73c768a5b.png)

Now, changing from `UEFI` to `AMD` shows this : 
![image](https://user-images.githubusercontent.com/14914796/167248902-64b59565-79ce-4d67-b815-85dd8c3e21da.png)

I wish there were also a channel IRC or Matrix or whatever where I could contact the devs and see with them if this is really a bug, if I should really open an issue or not.

**Comment by orangecms** [comment]
Ugh, I had not come back to this - has long been resolved; the wiring was just missing to actually pass on the size information from the analysis result. :sweat_smile: 

![image](https://github.com/user-attachments/assets/913bd29d-5d1a-4db4-8734-c723371b774f)

6d56301c42f86f597b96e6543f72f6d68fc62713 resolved this.

We do have a Matrix channel by now; https://fiedka.app/ has the link.
